---
title: "data import"
author: "Kristen Fedak"
date: "12/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(janitor)
```

# Load initial dataset 

* data = "all data" export from RedCap on 12/5/2019
* The .R file generated by redcap loads the .csv, edits data labels and levels, and saves a .rds output. 

```{r}
data <- read.csv("data/input/ASmokingCessationTri_DATA_2019-12-05_1313.csv")
event_names <- as.data.frame(unique(data$redcap_event_name))
```

# split into multiple data files

```{r}
baseline_participant_info <- data %>%
  dplyr::filter(grepl("baseline_arm", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")

follow_ups <- data %>%
  dplyr::filter(!grepl("baseline_arm", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")

two_week_visit <- data %>%
  dplyr::filter(grepl("2_week_visit|2week", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")

one_month_visit <- data %>%
  dplyr::filter(grepl("1_month|1mo", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")

one_yr_visit <- data %>%
  dplyr::filter(grepl("12_month|12mos", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")

two_month_visit <- data %>%
  dplyr::filter(grepl("2_month|2mos", redcap_event_name)) %>%
  dplyr::filter(!grepl("12_month|12mos", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")


three_month_visit <- data %>%
  dplyr::filter(grepl("3_month|3mos", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")


six_month_visit <- data %>%
  dplyr::filter(grepl("6_month|6mos", redcap_event_name)) %>%
  janitor::remove_empty(which = "cols")
```

